name: 'SaveFile'
description: 'Save file with configured content'
inputs:
  filePath:  
    description: 'The file path where to save file'
    required: true
  content:  
    description: 'The content'
    required: true    
runs:
  using: 'node12'
  main: 'dist/index.js'
