name: Local File Creation
description: 'Saves local with configured content'
author: Petr Pokorny

inputs:
  filePath:  
    description: 'The file path where to save file'
    required: true
  content:  
    description: 'The content'
    required: true    
  doubleQuotesToSingle:
    description: 'If true, the action replaces "" to " in the content string'    
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
