name: Local File Creation
description: 'Saves local with configured content'
author: Petr Pokorny

inputs:
  filePath:  
    description: 'The file path where to save file'
    required: true
  content:  
    description: 'The content'
    required: true    
runs:
  using: 'node12'
  main: 'dist/index.js'
